apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx3-pipeline-catalog
      changes:
        - regex:
            pattern: "ghcr.io/jenkins-x-plugins/jx-admin:(.*)"
            files:
              - "**/*.yaml"
    - urls:
        - https://github.com/jenkins-x/jx-cli
      changes:
        - regex:
            pattern: |
              \s+AdminVersion = "(.*)"
            files:
              - "pkg/plugins/versions.go"
